Vagrant.configure(2) do |config|

  config.vm.define "jenkins_test" do |jenkins_test|
    jenkins_test.vm.box = "centos/7"
    jenkins_test.vm.hostname = "jenkins"
    jenkins_test.vm.network "private_network", ip: "172.42.42.105"
    jenkins_test.vm.provider "virtualbox" do |v|
      v.name = "jenkins_test"
      v.memory = 1024
      v.cpus = 1
    end
    jenkins_test.vm.provision "shell", path: "install_jenkins.sh"
  end

end
