Vagrant.configure(2) do |config|

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "centos/7"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "172.42.42.103"
    jenkins.vm.provider "virtualbox" do |v|
      v.name = "jenkins"
      v.memory = 1024
      v.cpus = 1
    end
    jenkins.vm.provision "shell", path: "install_jenkins.sh"
  end

end
