Vagrant.configure(2) do |config|

  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "centos/7"
    centos7.vm.hostname = "centos7.example.com"
    centos7.vm.network "private_network", ip: "172.42.42.103"
    centos7.vm.provider "virtualbox" do |v|
      v.name = "centos7"
      v.memory = 2048
      v.cpus = 2
    end
    centos7.vm.provision  "shell", path: "install.sh" 
  end

end
