Vagrant.configure(2) do |config|

  config.vm.define "ubutu18" do |centos7|
    centos7.vm.box = "ubuntu/bionic64"
    centos7.vm.hostname = "ubuntu18.example.com"
    centos7.vm.network "private_network", ip: "172.42.42.106"
    centos7.vm.provider "virtualbox" do |v|
      v.name = "ubuntu18"
      v.memory = 2048
      v.cpus = 2
    end
    # ubuntu18.vm.provision  "shell", path: "install.sh" 
  end

end
